/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard;

import com.sun.glass.events.KeyEvent;
import dammikatex.login;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.Timer;
import database.Connectionget;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.DateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import viewSaleM.NewCustomer;

//imported for printing Bill
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dinuja pinto
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    String code;
    String prname;
    String price;
    String disc;
    double finalTot = 0;
    double amt = 0;
    double pamt = 0;
    double ramt = 0;
    
    //SetIcon
    ImageIcon icon;

    Timer timer;

    int z = 0;

    //item wise
    int inot = 0;

    //print Bill
    int bHeight = 0;

    public Dashboard() {
        initComponents();
        //For center to window --------------------------------
        Toolkit toolkitobj1 = getToolkit();
        Dimension size = toolkitobj1.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        //setTitle
        //setTitle("DHAMMIKA Tex - SALES");
        
        //setIcon
        icon = new ImageIcon("E:\\SLIIT Hub\\2nd year\\2nd Sem\\IT Project\\project\\zzImpliment2\\dammikaLogo2.jpg");
        setIconImage(icon.getImage());

        //Hide sale report buttons
        billWise.setVisible(false);
        itemWise.setVisible(false);
        jLabel27.setVisible(false);
        jLabel25.setVisible(false);

        //SET DATE TIME TO BILL
        ActionListener actionListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //set 24 Time
                Date Time = new Date();
                DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
                String time = timeFormat.format(Time);
                TimeLb.setText(time);

                //set Date
                Date date = new Date();
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
                String Date = dateFormat.format(date);
                DateLb.setText(Date);
            }
        };
        timer = new Timer(1000, actionListener);
        timer.setInitialDelay(0);
        timer.start();

        //Auto set Bill No for new Bill
        try {
            Connection con = Connectionget.getInstatnce().getConnection();
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("SELECT MAX(Bill_No) FROM bill");

            if (rs.next()) {
                int billNumber = rs.getInt(1) + 1;
                billNo.setText(Integer.toString(billNumber));
            }

        } catch (HeadlessException | SQLException e) {

            billNo.setText("NO.!");
            billNo.setForeground(new Color(243, 0, 0, 255));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

        //panal startup visible
        bill.setVisible(false);

        //Buttons
        ADD.setEnabled(false);
        RemoveProduct.setEnabled(false);
        printSave.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newCus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        saleReport = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        billWise = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        itemWise = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        issueVo = new javax.swing.JButton();
        bill = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DateLb = new javax.swing.JLabel();
        TimeLb = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        billNo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        cusNicBill = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CusNameBill = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cusPhoneBill = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cusEmailBill = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Pcode = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        ADD = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        Pname = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        printSave = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        ReAmt = new javax.swing.JTextField();
        painAmt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Finaltotal = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        RemoveProduct = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        billTable = new javax.swing.JTable();
        invalid = new javax.swing.JLabel();
        Pinvalid = new javax.swing.JLabel();
        billDone = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        billBack = new javax.swing.JLabel();
        voucherHis = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newCus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/new buyer.png"))); // NOI18N
        newCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCusActionPerformed(evt);
            }
        });
        getContentPane().add(newCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 11, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("New Customer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 92, 94, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Voucher History");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 110, -1));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Issue Voucher");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 90, 90, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/buyer Details.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Customer Details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 100, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Billing");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/Update buyer.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 11, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/billing.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Update Customer");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        saleReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/control hide and show.png"))); // NOI18N
        saleReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saleReportMouseClicked(evt);
            }
        });
        getContentPane().add(saleReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Item Wise");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 70, -1));

        billWise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/billwise.png"))); // NOI18N
        billWise.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                billWiseComponentShown(evt);
            }
        });
        billWise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billWiseActionPerformed(evt);
            }
        });
        getContentPane().add(billWise, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 100, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("SALES Report");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 100, -1));

        itemWise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/itemwise.png"))); // NOI18N
        itemWise.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                itemWiseComponentShown(evt);
            }
        });
        itemWise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemWiseActionPerformed(evt);
            }
        });
        getContentPane().add(itemWise, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, -1, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel27.setText("Bill Wise");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, -1, -1));

        issueVo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/new product.png"))); // NOI18N
        issueVo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueVoActionPerformed(evt);
            }
        });
        getContentPane().add(issueVo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        bill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/billing.png"))); // NOI18N
        bill.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 12, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("DHAMMIKA TEX");
        bill.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 25, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("SALES");
        bill.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 31, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Date :");
        bill.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, -1, -1));

        DateLb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DateLb.setText("jLabel4");
        bill.add(DateLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, -1));

        TimeLb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TimeLb.setText("jLabel6");
        bill.add(TimeLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Time :");
        bill.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, -1, -1));

        billNo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        billNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        billNo.setToolTipText("");
        bill.add(billNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 110, 30));
        bill.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1160, 10));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("NIC");
        bill.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 30));

        cusNicBill.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cusNicBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusNicBillActionPerformed(evt);
            }
        });
        bill.add(cusNicBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 170, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Name");
        bill.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, 30));

        CusNameBill.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bill.add(CusNameBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 240, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Phone");
        bill.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, 30));

        cusPhoneBill.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bill.add(cusPhoneBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 170, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Email");
        bill.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, -1, 30));

        cusEmailBill.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cusEmailBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusEmailBillActionPerformed(evt);
            }
        });
        bill.add(cusEmailBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 230, 30));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Customer Details :");
        bill.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        bill.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1160, 10));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Product Details :");
        bill.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Product Code");
        bill.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        Pcode.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Pcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PcodeActionPerformed(evt);
            }
        });
        Pcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PcodeKeyReleased(evt);
            }
        });
        bill.add(Pcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 170, 30));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("Quantity");
        bill.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, 30));

        qty.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bill.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 170, 30));

        ADD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/add.png"))); // NOI18N
        ADD.setText("ADD");
        ADD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        bill.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, -1, 40));
        bill.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1160, 10));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("Product Name");
        bill.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, 30));

        Pname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bill.add(Pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 170, 30));

        btnReset.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/Reset.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        bill.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 480, -1, 40));

        printSave.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        printSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/save.png"))); // NOI18N
        printSave.setText("Save & Print");
        printSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printSaveActionPerformed(evt);
            }
        });
        bill.add(printSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, -1, 40));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("Return Amount");
        bill.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, -1, 30));

        ReAmt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bill.add(ReAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 420, 180, 30));

        painAmt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        painAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                painAmtActionPerformed(evt);
            }
        });
        bill.add(painAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 380, 180, 30));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setText("Paid Amount");
        bill.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, -1, 30));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setText("Total");
        bill.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, -1, 30));

        Finaltotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bill.add(Finaltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, 180, 30));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setText("Calculation Details :");
        bill.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, -1, -1));

        RemoveProduct.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        RemoveProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/delete.png"))); // NOI18N
        RemoveProduct.setText("Remove");
        RemoveProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RemoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveProductActionPerformed(evt);
            }
        });
        bill.add(RemoveProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 120, 40));

        jButton8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/close Jframe.png"))); // NOI18N
        jButton8.setText("Close");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        bill.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 260, -1, 40));

        billTable.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        billTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product code", "Product Name", "Price", "Qty", "Discount", "Amount"
            }
        ));
        billTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(billTable);

        bill.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 730, 290));

        invalid.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bill.add(invalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 120, 20));

        Pinvalid.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Pinvalid.setToolTipText("");
        bill.add(Pinvalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 110, 20));

        billDone.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        billDone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bill.add(billDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 70, 30));

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel32.setText("BILL NO");
        bill.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 19, -1, 30));

        billBack.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        billBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/billing background.png"))); // NOI18N
        bill.add(billBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 1160, 550));

        voucherHis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/details product.png"))); // NOI18N
        voucherHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voucherHisActionPerformed(evt);
            }
        });
        getContentPane().add(voucherHis, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/logout.png"))); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, -1, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/Close.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, -1, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel30.setText("LogOut");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 90, -1, -1));

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Close");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 90, 90, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 710, 220, 30));

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel33.setText("User :");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 710, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/home.PNG"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCusActionPerformed
        // TODO add your handling code here:
        new viewSaleM.NewCustomer().setVisible(true);
    }//GEN-LAST:event_newCusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new viewSaleM.CustomerDetails().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new viewSaleM.UpdateCustomer().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        bill.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cusEmailBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusEmailBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusEmailBillActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        cusNicBill.setText("");
        CusNameBill.setText("");
        cusPhoneBill.setText("");
        cusEmailBill.setText("");
        Pcode.setText("");
        Pname.setText("");
        qty.setText("");
        Finaltotal.setText("");
        painAmt.setText("");
        ReAmt.setText("");
        billDone.setText("");
        //Auto increment and set Bill No for new Bill
        try {
            Connection con = Connectionget.getInstatnce().getConnection();
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("SELECT MAX(Bill_No) FROM bill");

            if (rs.next()) {
                int billNumber = rs.getInt(1) + 1;
                billNo.setText(Integer.toString(billNumber));
            }

        } catch (HeadlessException | SQLException e) {

            billNo.setText("NO.!");
            billNo.setForeground(new Color(243, 0, 0, 255));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

        //clear table
        removeAllDataFromJTable(billTable);

        finalTot = 0;
        amt = 0;
        pamt = 0;
        ramt = 0;

        RemoveProduct.setEnabled(false);
        printSave.setEnabled(false);
        /*DefaultTableModel model = (DefaultTableModel)billTable.getModel();
       model.removeRow(0);*/
    }//GEN-LAST:event_btnResetActionPerformed

    public static void removeAllDataFromJTable(JTable table) {

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int numberOfRows = table.getRowCount();

        int rowCounter = 0;

        //we will travel to every row and clean it
        for (rowCounter = 0; rowCounter < numberOfRows; rowCounter++) {

            model.removeRow(0);
        }
    }
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        bill.setVisible(false);

    }//GEN-LAST:event_jButton8ActionPerformed

    private void cusNicBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusNicBillActionPerformed
        // TODO add your handling code here:
        String nic = cusNicBill.getText();

        try {
            Connection con = Connectionget.getInstatnce().getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from customer where nic like '" + nic + "%'");

            if (rs.next()) {
                cusNicBill.setText(rs.getString("nic"));
                CusNameBill.setText(rs.getString("name"));
                cusPhoneBill.setText(rs.getString("phone"));
                cusEmailBill.setText(rs.getString("email"));
                invalid.setText("");
            } else {
                CusNameBill.setText("");
                cusPhoneBill.setText("");
                cusEmailBill.setText("");
                invalid.setText("Not Exit");
                invalid.setForeground(new Color(243, 0, 0, 255));
            }

        } catch (HeadlessException | SQLException e) {
            System.out.println(e);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cusNicBillActionPerformed

    private void PcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PcodeActionPerformed
        // TODO add your handling code here:

        String Prcode = Pcode.getText();

        try {
            Connection con = Connectionget.getInstatnce().getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from item where barcode like '" + Prcode + "%'");

            if (rs.next()) {

                //String code = rs.getString(1);
                String pname = rs.getString(3);

                Pcode.setText(rs.getString(1));
                Pname.setText(pname);
                qty.setText("1");
                Pinvalid.setText("");
                ADD.setEnabled(true);
            } else {
                Pname.setText("");
                qty.setText("");

                Pinvalid.setText("Not Exit");
                Pinvalid.setForeground(new Color(243, 0, 0, 255));
                ADD.setEnabled(false);
            }

        } catch (HeadlessException | SQLException e) {
            System.out.println(e);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PcodeActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        // TODO add your handling code here:
        String Prcode = Pcode.getText();

        try {
            Connection con = Connectionget.getInstatnce().getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from item where barcode like '" + Prcode + "%'");

            if (rs.next()) {

                code = rs.getString(1);
                prname = rs.getString(3);
                price = rs.getString(2);
                disc = rs.getString(6);

            }

        } catch (HeadlessException | SQLException e) {
            System.out.println(e);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

        double Pprice = Double.parseDouble(price);
        double Pdisc = Double.parseDouble(disc);
        int Pqty = Integer.parseInt(qty.getText());

        amt = (Pprice - Pdisc) * Pqty;

        DefaultTableModel model = (DefaultTableModel) billTable.getModel();
        model.addRow(new Object[]{code, prname, price, qty.getText(), disc, amt});

        finalTot = finalTot + amt;

        String FT = String.valueOf(finalTot);

        Finaltotal.setText(FT);

        Pcode.setText("");
        Pname.setText("");
        qty.setText("");

        RemoveProduct.setEnabled(false);
        ADD.setEnabled(false);


    }//GEN-LAST:event_ADDActionPerformed

    private void PcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PcodeKeyReleased
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
            Pinvalid.setText("");
            ADD.setEnabled(false);
        }

        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            Pinvalid.setText("");
        }

    }//GEN-LAST:event_PcodeKeyReleased

    private void painAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_painAmtActionPerformed
        // TODO add your handling code here:

        String vou = painAmt.getText();
        int na = vou.length();
        String le = vou.substring(0, 1);
        String vnum = vou.substring(1, na);

        if ("v".equals(le) || "V".equals(le)) {

            try {
                Connection con = Connectionget.getInstatnce().getConnection();
                PreparedStatement pstm = con.prepareStatement("select * from voucher where voucher_ID ='" + vnum + "'");
                ResultSet rs = pstm.executeQuery();

                if (rs.next()) {
                    String sts = rs.getString("Status");
                    if ("Used".equals(sts)) {
                        ReAmt.setText("Used Voucher");
                        ReAmt.setForeground(new Color(243, 0, 0, 255));
                    } else {
                        ReAmt.setText("Gift Voucher");
                        ReAmt.setForeground(new Color(28, 147, 47, 255));

                        try {

                            Statement st = con.createStatement();
                            st.executeUpdate("update voucher set Status='Used' where voucher_ID ='" + vnum + "' ");
                            printSave.setEnabled(true);
                            System.out.println("OK");
                        } catch (HeadlessException | SQLException e) {
                            System.out.println("No baby");
                        }
                    }
                } else {
                    //JOptionPane.showMessageDialog(null, "Customer does not exit");
                    ReAmt.setText("Not Exit");
                    ReAmt.setForeground(new Color(243, 0, 0, 255));
                }

            } catch (HeadlessException | SQLException e) {
                System.out.println("No baby");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }

            //ReAmt.setText("Gift Voucher");
        } else {

            pamt = Double.parseDouble(painAmt.getText());

            ramt = pamt - finalTot;

            String Ramt = String.valueOf(ramt);

            ReAmt.setText(Ramt);
            ReAmt.setForeground(new Color(18, 30, 49));

            printSave.setEnabled(true);
        }


    }//GEN-LAST:event_painAmtActionPerformed

    private void RemoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveProductActionPerformed
        // TODO add your handling code here:
        int row = billTable.getSelectedRow();

        String cell = billTable.getModel().getValueAt(row, 5).toString();
        double cellAmt = Double.parseDouble(cell);

        finalTot = finalTot - cellAmt;

        String cFT = String.valueOf(finalTot);

        Finaltotal.setText(cFT);

        DefaultTableModel model = (DefaultTableModel) billTable.getModel();
        model.removeRow(row);

        RemoveProduct.setEnabled(false);
    }//GEN-LAST:event_RemoveProductActionPerformed

    private void billTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTableMouseClicked
        // TODO add your handling code here:
        RemoveProduct.setEnabled(true);
    }//GEN-LAST:event_billTableMouseClicked

    private void printSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printSaveActionPerformed
        // TODO add your handling code here:
        String no = billNo.getText();
        String date = DateLb.getText();
        String time = TimeLb.getText();
        String cnic = cusNicBill.getText();
        String cname = CusNameBill.getText();
        String cphone = cusPhoneBill.getText();
        String billTot = Finaltotal.getText();

        //Bill wise 
        try {
            Connection con = Connectionget.getInstatnce().getConnection();
            Statement st = con.createStatement();
            st.executeUpdate("insert into bill values ('" + no + "','" + date + "','" + time + "','" + cnic + "','" + cname + "','" + cphone + "','" + billTot + "')");

            billDone.setText("Done.!");
            billDone.setForeground(new Color(28, 147, 47, 255));

        } catch (HeadlessException | SQLException e) {

            billDone.setText("NO.!");
            billDone.setForeground(new Color(243, 0, 0, 255));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Item wise
        try {
            Connection con = Connectionget.getInstatnce().getConnection();
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("SELECT MAX(no) FROM itemwise");

            if (rs.next()) {
                inot = rs.getInt(1) + 1;

            }

        } catch (HeadlessException | SQLException e) {

            System.out.println("get Max :" + e);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Bill wise
        String bno = billNo.getText();
        String bdate = DateLb.getText();
        try {
            Connection con = Connectionget.getInstatnce().getConnection();
            Statement st = con.createStatement();

            for (int i = 0; i < billTable.getRowCount(); i++) {

                String pCode = billTable.getValueAt(i, 0).toString();
                String pName = billTable.getValueAt(i, 1).toString();
                String Qty = billTable.getValueAt(i, 3).toString();

                st.executeUpdate("insert into itemwise values ('" + inot + "','" + bno + "','" + bdate + "','" + pCode + "','" + pName + "','" + Qty + "')");
                inot = inot + 1;
            }

        } catch (HeadlessException | SQLException e) {

            System.out.println(e);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Update stock qty
        try {
            Connection con = Connectionget.getInstatnce().getConnection();
            Statement st = con.createStatement();

            for (int i = 0; i < billTable.getRowCount(); i++) {

                String pCode = billTable.getValueAt(i, 0).toString();

                String Qty = billTable.getValueAt(i, 3).toString();
                int bqty = Integer.parseInt(Qty);

                String sqty = null;
                PreparedStatement pstm = con.prepareStatement("select Quantity from stock where Item_ID ='" + pCode + "'");
                ResultSet rs = pstm.executeQuery();
                if (rs.next()) {
                    sqty = rs.getString("Quantity");
                }

                int isqty = Integer.parseInt(sqty);

                int fQty = isqty - bqty;

                st.executeUpdate("update stock set Quantity='" + fQty + "' where Item_ID ='" + pCode + "' ");
            }
            System.out.println("Stock Updated");
        } catch (HeadlessException | SQLException e) {
            System.out.println("Stock not Update:" + e);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Printing Bill
        bHeight = billTable.getRowCount();

        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setPrintable(new BillPrintable(), getPageFormat(pj));
        try {
            pj.print();

        } catch (PrinterException ex) {
            System.out.println(ex);
        }

        printSave.setEnabled(false);
    }//GEN-LAST:event_printSaveActionPerformed

    private void saleReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleReportMouseClicked
        // TODO add your handling code here:
        if (z == 0) {
            z = 1;
            try {
                Thread.sleep(200);
                billWise.setVisible(true);
                jLabel27.setVisible(true);
            } catch (InterruptedException e) {
                System.out.println(e);
            }
        } else {
            billWise.setVisible(false);
            itemWise.setVisible(false);
            jLabel27.setVisible(false);
            jLabel25.setVisible(false);
            z = 0;
        }
    }//GEN-LAST:event_saleReportMouseClicked

    private void billWiseComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_billWiseComponentShown
        // TODO add your handling code here:
        try {
            Thread.sleep(200);
            itemWise.setVisible(true);
            jLabel25.setVisible(true);
        } catch (InterruptedException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_billWiseComponentShown

    private void itemWiseComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_itemWiseComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_itemWiseComponentShown

    private void billWiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billWiseActionPerformed
        // TODO add your handling code here:
        new viewSaleM.BillWiseR().setVisible(true);
    }//GEN-LAST:event_billWiseActionPerformed

    private void itemWiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemWiseActionPerformed
        // TODO add your handling code here:
        new viewSaleM.ItemWisR().setVisible(true);
    }//GEN-LAST:event_itemWiseActionPerformed

    private void issueVoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueVoActionPerformed
        // TODO add your handling code here:
        new viewSaleM.VoucherIssue().setVisible(true);
    }//GEN-LAST:event_issueVoActionPerformed

    private void voucherHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voucherHisActionPerformed
        // TODO add your handling code here:
        new viewSaleM.VoucherHistory().setVisible(true);


    }//GEN-LAST:event_voucherHisActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do You Want to Close..?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            //System.exit(0);
            setVisible(false);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do You Want to Logout", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    //Bill Printing Methods strating from here
    public PageFormat getPageFormat(PrinterJob pj) {

        PageFormat pf = pj.defaultPage();
        Paper paper = pf.getPaper();

        double bodyHeight = bHeight;
        double headerHeight = 5.0;
        double footerHeight = 5.0;
        double width = cm_to_pp(8);
        double height = cm_to_pp(headerHeight + bodyHeight + footerHeight);
        paper.setSize(width, height);
        paper.setImageableArea(0, 10, width, height - cm_to_pp(1));

        pf.setOrientation(PageFormat.PORTRAIT);
        pf.setPaper(paper);

        return pf;
    }

    protected static double cm_to_pp(double cm) {
        return toPPI(cm * 0.393600787);
    }

    protected static double toPPI(double inch) {
        return inch * 72d;
    }

    public class BillPrintable implements Printable {

        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex)
                throws PrinterException {

            int r = billTable.getRowCount();
            ImageIcon icon = new ImageIcon("E:\\SLIIT Hub\\2nd year\\2nd Sem\\IT Project\\project\\zzImpliment2\\DammikaTex\\src\\Saleicon\\dammikaLogo.jpg");
            int result = NO_SUCH_PAGE;
            if (pageIndex == 0) {

                Graphics2D g2d = (Graphics2D) graphics;
                double width = pageFormat.getImageableWidth();
                g2d.translate((int) pageFormat.getImageableX(), (int) pageFormat.getImageableY());

                //  FontMetrics metrics=g2d.getFontMetrics(new Font("Arial",Font.BOLD,7));
                try {
                    int y = 20;
                    int yShift = 10;
                    int headerRectHeight = 15;
                    // int headerRectHeighta=40;

                    g2d.setFont(new Font("Monospaced", Font.PLAIN, 9));
                    g2d.drawImage(icon.getImage(), 50, 20, 90, 30, rootPane);
                    y += yShift + 30;
                    g2d.drawString("-------------------------------------", 12, y);
                    y += yShift;
                    g2d.drawString("           Dhammika Tex        ", 12, y);
                    y += yShift;
                    g2d.drawString("       No 15, CIRCLE ROAD ", 12, y);
                    y += yShift;
                    g2d.drawString("            MIRIGAMA ", 12, y);
                    y += yShift;
                    g2d.drawString("   FACEBOOK PAGE-DHAMMIKA TEX ", 12, y);
                    y += yShift;
                    g2d.drawString("        TEL : +94700000000      ", 12, y);
                    y += yShift;
                    g2d.drawString("Bill No :  " + billNo.getText(), 12, y);
                    y += yShift;
                    g2d.drawString("-------------------------------------", 12, y);
                    y += headerRectHeight;

                    g2d.drawString(" Item Name/   ", 10, y);
                    y += yShift;
                    g2d.drawString(" PRICE     QTY     DIS     AMOUNT   ", 10, y);
                    y += yShift;
                    g2d.drawString("-------------------------------------", 10, y);
                    y += headerRectHeight;

                    for (int s = 0; s < r; s++) {

                        String productN = billTable.getValueAt(s, 1).toString();
                        String price = billTable.getValueAt(s, 2).toString();
                        String qty = billTable.getValueAt(s, 3).toString();
                        String dis = billTable.getValueAt(s, 4).toString();
                        String amt = billTable.getValueAt(s, 5).toString();

                        g2d.drawString(" " + productN + "                            ", 10, y);
                        y += yShift;
                        g2d.drawString(" " + price + "        " + qty + "      " + dis, 10, y);
                        g2d.drawString(amt, 160, y);
                        y += yShift;

                    }

                    g2d.drawString("-------------------------------------", 10, y);
                    y += yShift;
                    g2d.drawString(" Total amount:              " + Finaltotal.getText() + "   ", 10, y);
                    y += yShift;
                    g2d.drawString("-------------------------------------", 10, y);
                    y += yShift;
                    g2d.drawString(" Cash      :               " + painAmt.getText() + "   ", 10, y);
                    y += yShift;
                    g2d.drawString("-------------------------------------", 10, y);
                    y += yShift;
                    g2d.drawString(" Balance   :            " + ReAmt.getText() + "   ", 10, y);
                    y += yShift;

                    g2d.drawString("*************************************", 10, y);
                    y += yShift;
                    g2d.drawString("       THANK YOU COME AGAIN            ", 10, y);
                    y += yShift;
                    g2d.drawString("*************************************", 10, y);
                    y += yShift;
                    g2d.drawString("     SOFTWARE BY:Dinuja Pinto          ", 10, y);
                    y += yShift;
                    /*g2d.drawString("   CONTACT: pinto.dinuja@gmail.com       ", 10, y);
                    y += yShift;*/

                } catch (Exception e) {
                    System.out.println(e);
                }

                result = PAGE_EXISTS;
            }
            return result;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JTextField CusNameBill;
    private javax.swing.JLabel DateLb;
    private javax.swing.JTextField Finaltotal;
    private javax.swing.JTextField Pcode;
    private javax.swing.JLabel Pinvalid;
    private javax.swing.JTextField Pname;
    private javax.swing.JTextField ReAmt;
    private javax.swing.JButton RemoveProduct;
    private javax.swing.JLabel TimeLb;
    private javax.swing.JPanel bill;
    private javax.swing.JLabel billBack;
    private javax.swing.JLabel billDone;
    private javax.swing.JLabel billNo;
    private javax.swing.JTable billTable;
    private javax.swing.JButton billWise;
    private javax.swing.JButton btnExit;
    public javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField cusEmailBill;
    private javax.swing.JTextField cusNicBill;
    private javax.swing.JTextField cusPhoneBill;
    private javax.swing.JLabel invalid;
    private javax.swing.JButton issueVo;
    private javax.swing.JButton itemWise;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton newCus;
    private javax.swing.JTextField painAmt;
    private javax.swing.JButton printSave;
    private javax.swing.JTextField qty;
    private javax.swing.JButton saleReport;
    private javax.swing.JButton voucherHis;
    // End of variables declaration//GEN-END:variables
}
