/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewSaleM;

/**
 *
 * @author Dinuja pinto
 */
import com.itextpdf.*;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import static com.itextpdf.text.html.HtmlTags.P;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import database.Connectionget;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
public class ItemWisR extends javax.swing.JFrame {

    /**
     * Creates new form ItemWisR
     */
    public ItemWisR() {
        initComponents();
        //For center to window --------------------------------
        Toolkit toolkitobj1 = getToolkit();
        Dimension size = toolkitobj1.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        viewResult = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        close = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/itemwise.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 12, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel2.setText("Item Wise Sale Report");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 82, 1145, 10));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Date  From");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 96, -1, 31));

        jDateChooser1.setDateFormatString("yyyy/MM/dd");
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 96, 150, 31));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("To");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 96, -1, 31));

        jDateChooser2.setDateFormatString("yyyy/MM/dd");
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 96, 150, 31));

        viewResult.setBackground(new java.awt.Color(0, 0, 255));
        viewResult.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        viewResult.setForeground(new java.awt.Color(255, 255, 255));
        viewResult.setText("View Result");
        viewResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewResultActionPerformed(evt);
            }
        });
        getContentPane().add(viewResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 97, -1, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 141, 1145, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "no", "Bill_No", "Date", "Product_Code", "Product_Name", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1130, 310));

        close.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/close Jframe.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 490, -1, 40));

        print.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/print.png"))); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 100, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/reportbackground - Copy.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewResultActionPerformed
        // TODO add your handling code here:

        

        java.util.Date from=jDateChooser1.getDate();
        java.util.Date to=jDateChooser2.getDate();

        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        String DateFrom = dateFormat.format(from);
        String DateTo = dateFormat.format(to);

         System.out.println(DateFrom);
         System.out.println(DateTo);

        try {
            Connection con = Connectionget.getInstatnce().getConnection();
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("select * from itemwise where Date between '"+DateFrom+"' and '"+DateTo+"' ");

            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (HeadlessException | SQLException e) {

            System.out.println(e);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemWisR.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_viewResultActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        java.util.Date from=jDateChooser1.getDate();
        java.util.Date to=jDateChooser2.getDate();
        
        
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String DateFrom = dateFormat.format(from);
        String DateTo = dateFormat.format(to);
        
        String path = "E:\\SLIIT Hub\\2nd year\\2nd Sem\\IT Project\\project\\zzImpliment2\\printed\\Dammika Tex\\Item wise report\\";
        
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        
        try{
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+DateFrom+" To "+DateTo+".pdf"));
            doc.open();
            
            Paragraph para1 = new Paragraph("DHAMMIKA Tex\nItem Wise Sale Report");
            doc.add(para1);
            
            Paragraph para2 = new Paragraph("Date: From  "+DateFrom+"  To   "+DateTo+"\n\n");
            doc.add(para2);
            
            PdfPTable tbl = new PdfPTable(6);
            tbl.addCell("no");
            tbl.addCell("Bill_No");
            tbl.addCell("Date");
            tbl.addCell("Product_Code");
            tbl.addCell("Product_Name");
            tbl.addCell("Qty");
            
            
            for(int i=0;i<jTable1.getRowCount();i++){
                String no = jTable1.getValueAt(i, 0).toString();
                String billno = jTable1.getValueAt(i, 1).toString();
                String date = jTable1.getValueAt(i, 2).toString();
                String pNO = jTable1.getValueAt(i, 3).toString();
                String pName = jTable1.getValueAt(i, 4).toString();
                String qty = jTable1.getValueAt(i, 5).toString();
                
                
                tbl.addCell(no);
                tbl.addCell(billno);
                tbl.addCell(date);
                tbl.addCell(pNO);
                tbl.addCell(pName);
                tbl.addCell(qty);
                
            }
            doc.add(tbl);
            
            
            JOptionPane.showMessageDialog(null,"Report Generated");
            
        }catch(DocumentException | HeadlessException | FileNotFoundException e)
        {
            System.out.println(e);
        }
        
        doc.close();
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemWisR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemWisR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemWisR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemWisR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemWisR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton print;
    private javax.swing.JButton viewResult;
    // End of variables declaration//GEN-END:variables
}
