/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewSaleM;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import database.Connectionget;
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Dinuja pinto
 */
public class NewCustomer extends javax.swing.JFrame {

    /**
     * Creates new form NewCustomer
     */
    public NewCustomer() {
        initComponents();
        //For center to window --------------------------------
        Toolkit toolkitobj1 = getToolkit();
        Dimension size = toolkitobj1.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        phon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/new buyer.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 12, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel2.setText("New Customer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 24, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, 576, 10));

        nic.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nic.setForeground(new java.awt.Color(153, 153, 153));
        nic.setText("Enter NIC Number");
        nic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nicFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nicFocusLost(evt);
            }
        });
        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nicKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicKeyReleased(evt);
            }
        });
        getContentPane().add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 115, 250, 29));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("NIC");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 164, -1, -1));

        name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(153, 153, 153));
        name.setText("Enter Name");
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 159, 250, 29));

        phon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        phon.setForeground(new java.awt.Color(153, 153, 153));
        phon.setText("Enter Phone Number");
        phon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phonFocusLost(evt);
            }
        });
        phon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonActionPerformed(evt);
            }
        });
        phon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phonKeyReleased(evt);
            }
        });
        getContentPane().add(phon, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 206, 250, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Phone");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 254, -1, -1));

        email.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(153, 153, 153));
        email.setText("Enter Email");
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 251, 250, 30));

        address.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        address.setForeground(new java.awt.Color(153, 153, 153));
        address.setText("Enter Address");
        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFocusLost(evt);
            }
        });
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 294, 250, 29));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 299, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 331, 576, 10));

        reset.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/Reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, 39));

        close.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/close Jframe.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, 39));

        save.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/save.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, 39));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(30, 226, 16));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 270, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 257, 96, 29));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 118, 96, 29));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 210, 96, 29));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nicFocusGained
        // TODO add your handling code here:
        if (nic.getText().equals("Enter NIC Number")) {
            nic.setText("");
            nic.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_nicFocusGained

    private void nicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nicFocusLost
        // TODO add your handling code here:
        if (nic.getText().equals("")) {
            nic.setText("Enter NIC Number");
            nic.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_nicFocusLost

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicActionPerformed

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
        if (name.getText().equals("Enter Name")) {
            name.setText("");
            name.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
        if (name.getText().equals("")) {
            name.setText("Enter Name");
            name.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_nameFocusLost

    private void phonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonFocusGained
        // TODO add your handling code here:
        if (phon.getText().equals("Enter Phone Number")) {
            phon.setText("");
            phon.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_phonFocusGained

    private void phonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonFocusLost
        // TODO add your handling code here:
        if (phon.getText().equals("")) {
            phon.setText("Enter Phone Number");
            phon.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_phonFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if (email.getText().equals("Enter Email")) {
            email.setText("");
            email.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        if (email.getText().equals("")) {
            email.setText("Enter Email");
            email.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_emailFocusLost

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusGained
        // TODO add your handling code here:
        if (address.getText().equals("Enter Address")) {
            address.setText("");
            address.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_addressFocusGained

    private void addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusLost
        // TODO add your handling code here:
        if (address.getText().equals("")) {
            address.setText("Enter Address");
            address.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_addressFocusLost

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        jLabel12.setText("");
       
        name.setText("Enter Name");
        name.setForeground(new Color(153, 153, 153));

        nic.setText("Enter NIC Number");
        nic.setForeground(new Color(153, 153, 153));

        address.setText("Enter Address");
        address.setForeground(new Color(153, 153, 153));

        phon.setText("Enter Phone Number");
        phon.setForeground(new Color(153, 153, 153));

        email.setText("Enter Email");
        email.setForeground(new Color(153, 153, 153));

        if (phon.getText().equals("Enter Phone Number")) {
            jLabel10.setText("");
        }

        if (email.getText().equals("Enter Email")) {
            jLabel8.setText("");
        }

        jLabel9.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String Cnic = nic.getText();
        String Cname = name.getText();
        String Cphone = phon.getText();
        String Cemail = email.getText();
        String Cadd = address.getText();

        try {
            Connection con = Connectionget.getInstatnce().getConnection();
            Statement st = con.createStatement();
            st.executeUpdate("insert into customer values ('" + Cnic + "','" + Cname + "','" + Cphone + "','" + Cemail + "','" + Cadd + "')");
            //JOptionPane.showMessageDialog(null, "Add successfull");
            jLabel12.setText("Add successfull");
            jLabel12.setForeground(new Color(28,147,47,255));
            //setVisible(false);
            //new NewCustomer().setVisible(true);
        } catch (HeadlessException | SQLException e) {
           // JOptionPane.showMessageDialog(null, "Customer Allready exit");
           jLabel12.setText("Unsuccessfull");
            jLabel12.setForeground(new Color(243,0,0,255));
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_saveActionPerformed

    private void phonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonActionPerformed

    private void phonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonKeyPressed
        // TODO add your handling code here:
        String phone = phon.getText();

        int length = phone.length();

        char c = evt.getKeyChar();
        /*if(length<10){
                //phon.setEditable(true);
                jLabel10.setText("Invalid");
         }
        if(length == 9){
            jLabel10.setText("");
        }*/

        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            if (length < 10) {
                phon.setEditable(true);
                //jLabel10.setText("Invalid");
            } else {
                phon.setEditable(false);
                //jLabel10.setText("");
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                phon.setEditable(true);
            } else {
                phon.setEditable(false);
            }
        }
    }//GEN-LAST:event_phonKeyPressed

    private void emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyPressed
        // TODO add your handling code here:
        /* String mail = email.getText();
        
        
        if(valEmail(mail) == false){
            jLabel8.setText("Invalid");
        }
        if(valEmail(mail) == true){
            jLabel8.setText("");
        }*/

    }//GEN-LAST:event_emailKeyPressed

    private void nicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyPressed
        // TODO add your handling code here:

        String ni = nic.getText();

        int len = ni.length();

        if (len < 10) {
            nic.setEditable(true);

        } else {
            nic.setEditable(false);

        }

        if (evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
            nic.setEditable(true);
        }


    }//GEN-LAST:event_nicKeyPressed

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        // TODO add your handling code here:
        String mail = email.getText();

        if (valEmail(mail) == false) {
            jLabel8.setText("Invalid");
        }
        if (valEmail(mail) == true) {
            jLabel8.setText("");
        }


    }//GEN-LAST:event_emailKeyReleased

    private void phonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonKeyReleased
        // TODO add your handling code here:
        String phone = phon.getText();

        int length = phone.length();

        //char c  = evt.getKeyChar();
        if (length < 10) {
            //phon.setEditable(true);
            jLabel10.setText("Invalid");
        }
        if (length == 10) {
            jLabel10.setText("");
        }

        /*if(evt.getKeyChar()>='0' && evt.getKeyChar() <= '9'){
            if(length<10){
                phon.setEditable(true);
                //jLabel10.setText("Invalid");
            }
            else {
                phon.setEditable(false);
                //jLabel10.setText("");
            }
        }else{
            if(evt.getExtendedKeyCode()== KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode()== KeyEvent.VK_DELETE){
                phon.setEditable(true);
            }
            else{
                phon.setEditable(false);
            }
        }*/
    }//GEN-LAST:event_phonKeyReleased

    private void nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyReleased
        // TODO add your handling code here:

        String ni = nic.getText();

        if (valNIC(ni) == false) {
            jLabel9.setText("Invalid");
            save.setEnabled(false);
        }
        if (valNIC(ni) == true) {
            jLabel9.setText("");
            save.setEnabled(true);
        }

        if (nic.getText().equals("Enter NIC Number")) {
            jLabel9.setText("");
        }
        
        jLabel12.setText("");
        
    }//GEN-LAST:event_nicKeyReleased

    public static boolean valNIC(String input) {
        String nicRegx = "^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][v/V]$";
        Pattern nicPat = Pattern.compile(nicRegx, Pattern.CASE_INSENSITIVE);
        Matcher match = nicPat.matcher(input);
        return match.find();
    }

    public static boolean valEmail(String input) {
        String emailRegx = "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$";
        Pattern emailPat = Pattern.compile(emailRegx, Pattern.CASE_INSENSITIVE);
        Matcher matcher = emailPat.matcher(input);
        return matcher.find();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton close;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField phon;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
