/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewSaleM;

import Dashboard.Dashboard;
import com.itextpdf.text.pdf.PdfWriter;
import database.Connectionget;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

//imported for printing Bill
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.FileOutputStream;
import javax.swing.ImageIcon;

/**
 *
 * @author Dinuja pinto
 */
public class VoucherIssue extends javax.swing.JFrame {

    /**
     * Creates new form VoucherIssue
     */
    //print Bill
    int bHeight = 0;

    public VoucherIssue() {
        initComponents();
        //For center to window --------------------------------
        Toolkit toolkitobj1 = getToolkit();
        Dimension size = toolkitobj1.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        try {
            Connection con = Connectionget.getInstatnce().getConnection();
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("SELECT MAX(voucher_ID) FROM voucher");

            if (rs.next()) {

                int vNumber = rs.getInt(1) + 1;
                vId.setText( Integer.toString(vNumber));
            }

        } catch (HeadlessException | SQLException e) {

            vId.setText("NO.!");
            vId.setForeground(new Color(243, 0, 0, 255));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VoucherIssue.class.getName()).log(Level.SEVERE, null, ex);
        }

        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();

        Idate.setText(dFormat.format(date));
        Idate.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Idate = new javax.swing.JTextField();
        value = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        printbtn = new javax.swing.JButton();
        resetbrn = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        vId = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel2.setText("Issue Voucher");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/new product.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 12, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 576, 10));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Voucher ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, 23));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Value (LKR)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, 29));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Issue Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 29));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Expire Date");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, 29));

        Idate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(Idate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 150, 29));

        value.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(value, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 150, 29));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 84, 576, 10));

        printbtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        printbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/print.png"))); // NOI18N
        printbtn.setText("Print");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });
        getContentPane().add(printbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, 40));

        resetbrn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        resetbrn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/Reset.png"))); // NOI18N
        resetbrn.setText("Reset");
        resetbrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbrnActionPerformed(evt);
            }
        });
        getContentPane().add(resetbrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, 40));

        closebtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/close Jframe.png"))); // NOI18N
        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, 40));

        jDateChooser1.setDateFormatString("yyyy/MM/dd");
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 140, 30));

        vId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(vId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 140, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 425, 180, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Saleicon/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        // TODO add your handling code here:

        java.util.Date exd = jDateChooser1.getDate();

        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        String DateFrom = dateFormat.format(exd);

        String vid = vId.getText();
        String val = value.getText();
        String idat = Idate.getText();

        try {
            Connection con = Connectionget.getInstatnce().getConnection();
            Statement st = con.createStatement();
            st.executeUpdate("insert into voucher values('" + vid + "','" + val + "','" + idat + "','" + DateFrom + "','not use')");

            jLabel4.setText("Successfull");
            jLabel4.setForeground(new Color(28, 147, 47, 255));

        } catch (HeadlessException | SQLException e) {

            jLabel4.setText("Unsuccessfull");
            jLabel4.setForeground(new Color(243, 0, 0, 255));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Printing voucher recipt
        bHeight = 5;

        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setPrintable(new BillPrintable(), getPageFormat(pj));
        try {
            pj.print();

        } catch (PrinterException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_printbtnActionPerformed

    private void resetbrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbrnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new VoucherIssue().setVisible(true);
    }//GEN-LAST:event_resetbrnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoucherIssue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoucherIssue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoucherIssue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoucherIssue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoucherIssue().setVisible(true);
            }
        });
    }

    //Voucher recit Printing Methods strating from here
    public PageFormat getPageFormat(PrinterJob pj) {

        PageFormat pf = pj.defaultPage();
        Paper paper = pf.getPaper();

        double bodyHeight = bHeight;
        double headerHeight = 5.0;
        double footerHeight = 5.0;
        double width = cm_to_pp(8);
        double height = cm_to_pp(headerHeight + bodyHeight + footerHeight);
        paper.setSize(width, height);
        paper.setImageableArea(0, 10, width, height - cm_to_pp(1));

        pf.setOrientation(PageFormat.PORTRAIT);
        pf.setPaper(paper);

        return pf;
    }

    protected static double cm_to_pp(double cm) {
        return toPPI(cm * 0.393600787);
    }

    protected static double toPPI(double inch) {
        return inch * 72d;
    }

    public class BillPrintable implements Printable {

        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex)
                throws PrinterException {

            java.util.Date exd = jDateChooser1.getDate();

            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
            String DateFrom = dateFormat.format(exd);
            
            
            
            ImageIcon icon = new ImageIcon("E:\\SLIIT Hub\\2nd year\\2nd Sem\\IT Project\\project\\zzImpliment2\\DammikaTex\\src\\Saleicon\\dammikaLogo.jpg");
            int result = NO_SUCH_PAGE;
            if (pageIndex == 0) {

                Graphics2D g2d = (Graphics2D) graphics;
                double width = pageFormat.getImageableWidth();
                g2d.translate((int) pageFormat.getImageableX(), (int) pageFormat.getImageableY());

                //  FontMetrics metrics=g2d.getFontMetrics(new Font("Arial",Font.BOLD,7));
                try {
                    
                    int y = 20;
                    int yShift = 10;
                    int headerRectHeight = 15;
                    

                    g2d.setFont(new Font("Monospaced", Font.PLAIN, 9));
                    g2d.drawImage(icon.getImage(), 50, 20, 90, 30, rootPane);
                    y += yShift + 30;
                    g2d.drawString("-------------------------------------", 12, y);
                    y += yShift;
                    g2d.drawString("           Dhammika Tex        ", 12, y);
                    y += yShift;
                    g2d.drawString("       No 15, CIRCLE ROAD ", 12, y);
                    y += yShift;
                    g2d.drawString("            MIRIGAMA ", 12, y);
                    y += yShift;
                    g2d.drawString("   FACEBOOK PAGE-DHAMMIKA TEX ", 12, y);
                    y += yShift;
                    g2d.drawString("        TEL : +94700000000      ", 12, y);
                    y += yShift;
                    
                    g2d.drawString("-------------------------------------", 12, y);
                    y += headerRectHeight;                   
                    
                    g2d.drawString("-------------------------------------", 10, y);
                    y += yShift;
                    g2d.drawString("      Voucher ID    : V" + vId.getText() + "   ", 10, y);
                    y += yShift;
                    g2d.drawString("      Value(LKR)    : " + value.getText() + "/= ", 10, y);
                    y += yShift;
                    
                    g2d.drawString("      Expire Date   : " + DateFrom + "   ", 10, y);
                    y += yShift;
                    
                    g2d.drawString("      Issue Date    : "+ Idate.getText() + "   ", 10, y);
                    y += yShift;

                    g2d.drawString("-------------------------------------", 12, y);
                    y += headerRectHeight;                   
                    
                    g2d.drawString("-------------------------------------", 10, y);
                    y += yShift;
                    g2d.drawString("*************************************", 10, y);
                    y += yShift;
                    g2d.drawString("       THANK YOU COME AGAIN            ", 10, y);
                    y += yShift;
                    g2d.drawString("*************************************", 10, y);
                    y += yShift;
                    g2d.drawString("     SOFTWARE BY:Dinuja Pinto          ", 10, y);
                    y += yShift;
                    /*g2d.drawString("   CONTACT: pinto.dinuja@gmail.com       ", 10, y);
                    y += yShift;*/

                } catch (Exception e) {
                    System.out.println(e);
                }

                result = PAGE_EXISTS;
            }
            return result;
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Idate;
    private javax.swing.JButton closebtn;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton printbtn;
    private javax.swing.JButton resetbrn;
    private javax.swing.JLabel vId;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
